### ISSUE TITLE
Column mismatch and parse errors

### ISSUE THREAD

**Issue by rubensworks** [PoDiGG/podigg-lc#1]
Occurs randomly with Docker.

```
info: >> Visualizing output
info: >> Exporting to GTFS
GTFS to linked connections converter use --help to discover more functions
Error reading calendar_dates.txt: Error: Parse Error: expected: '"' got: ':'. at ':["/node_m
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: expected: '"' got: ':'. at ':["/node_m
    at parseEscapedItem (/node_modules/fast-csv/lib/parser/parser.js:79:19)
    at ParserStream.parseLine [as parser] (/node_modules/fast-csv/lib/parser/parser.js:174:30)
    at ParserStream._parseLine [as _parse] (/node_modules/fast-csv/lib/parser/parser_stream.js:164:25)
    at ParserStream._transform (/node_modules/fast-csv/lib/parser/parser_stream.js:198:18)
    at ParserStream.Transform._read (_stream_transform.js:167:10)
    at ParserStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at ParserStream.Writable.write (_stream_writable.js:220:11)
    at ReadStream.ondata (_stream_readable.js:555:20)
```

```
Routes: +44Error reading routes.txt: Error: Unexpected Error: column header mismatch expected: 5 columns got: 7Routes: +110Error reading routes.txt: Error: Unexpected Error: column header mismatch expected: 5 columns got:
```

With parameters:
```
GTFS_GEN_SEED=111

GTFS_GEN_REGION__SIZE_X=2000 

GTFS_GEN_REGION__SIZE_Y=2000

GTFS_GEN_REGION__CELLS_PER_LATLON=200

GTFS_GEN_STOPS__STOPS=5000

GTFS_GEN_CONNECTIONS__DELAY_CHANCE=0.01

GTFS_GEN_CONNECTIONS__CONNECTIONS=800000

GTFS_GEN_ROUTES__ROUTES=5000

GTFS_GEN_ROUTES__MAX_ROUTE_LENGTH=50

GTFS_GEN_ROUTES__MIN_ROUTE_LENGTH=10 

GTFS_GEN_CONNECTIONS__ROUTE_CHOICE_POWER=1.3 

GTFS_GEN_CONNECTIONS__TIME_FINAL=63072000000 
```

**Comment by rubensworks** [comment]
Not reproducible by me on both Windows and Mac.

**Comment by rubensworks** [comment]
@petzkahe When you encounter this issue, what are the contents of the file that is being complained about?
