### ISSUE TITLE
Data generator exits with runtime error

### ISSUE THREAD

**Issue by Aklakan** [PoDiGG/podigg-lc#2]
```bash
docker run -it --rm \
-v $(pwd)/output_data:/tmp/output_data \
-e GTFS_GEN_SEED=123 \
podigg/podigg-lc
```

bails out with this error:
```bash
info: Generating with options:  seed=123
info: >> Generating stops
info: >> Generating edges
info: Clustering all stops
info: Clustering border stations
info: Connecting loose stops
info: >> Generating stops post-edges
info: >> Generating routes
info: Creating micro-routes
29 / 30
info: Creating macro-routes
info: >> Generating connections
info: >> Visualizing output
info: >> Exporting to GTFS
GTFS to linked connections converter use --help to discover more functions
Indexing services and trips succesful!
Connections: +29924
Routes: +4500
/node_modules/gtfs2lc/lib/StopsBuilder.js:31
        body['@graph'].forEach(function(element) {
                      ^

TypeError: Cannot read property 'forEach' of undefined
    at Request._callback (/node_modules/gtfs2lc/lib/StopsBuilder.js:31:23)
    at Request.self.callback (/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

**Comment by rubensworks** [comment]
It looks like your Docker container is not returning a proper response for the request to `http://irail.be/stations/NMBS`. Something may be wrong with your Docker network configuration.

Is it possible that you are using a proxy that returns a HTTP 200 status code for _all_ requests, even if they don't resolve?

**Comment by Aklakan** [comment]
I was not aware that the tool performs remote requests and it is not indicated in the output. So maybe the service was temporarily down or I had a bad connection. I just retried and it worked.
